# Generated by Django 4.0.3 on 2022-03-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=255)),
                ('bpub_date', models.DateTimeField(max_length=255)),
                ('bread', models.IntegerField(default=0)),
                ('bcomment', models.CharField(max_length=255)),
            ],
        ),
    ]
